volumes:
  data:

services:
  frontend:
    image: ghcr.io/janishutz/musicplayer-frontend
    ports:
      - 3000:3000

  backend:
    image: ghcr.io/janishutz/musicplayer
    volumes:
      - data:/app/data
      - ./config.yml:/app/config.yml
      - ./apple_private_key.p8:/app/apple_private_key.p8
    env_file: .env
    ports:
      - 8080:8080
